remove static stow
cus it relied on perl and stuff

diff --git a/bin/sync-dotfiles b/bin/sync-dotfiles
--- a/bin/sync-dotfiles
+++ b/bin/sync-dotfiles
@@ -5,9 +5,12 @@ DOTFILES_DIR="$HOME/dotfiles"
 if [ ! -d "$DOTFILES_DIR" ]; then
 	echo "failed to locate dotfiles directory"
 	exit 1
+elif ! command -v stow 1> /dev/null; then
+	echo "stow not found in PATH"
+	exit 1
 fi
 
-$HOME/dotfiles/.local/bin/stow --dir="$DOTFILES_DIR" --target="$HOME" --no-folding --verbose --stow .
+stow --dir="$DOTFILES_DIR" --target="$HOME" --no-folding --verbose --stow .
 
 echo "sync complete ($?)"
 
